"""add is_suspended to user model

Revision ID: 2655d0ec2d0f
Revises: fe1e93b4f258
Create Date: 2025-08-25 14:59:15.179722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2655d0ec2d0f'
down_revision = 'fe1e93b4f258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_suspended')

    # ### end Alembic commands ###
