"""add investment and investment plan models

Revision ID: 5894754c3479
Revises: 2655d0ec2d0f
Create Date: 2025-08-25 15:09:52.338933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5894754c3479'
down_revision = '2655d0ec2d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_plan_name'), ['name'], unique=True)

    op.create_table('investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['investment_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_start_date'), ['start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_start_date'))

    op.drop_table('investment')
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investment_plan_name'))

    op.drop_table('investment_plan')
    # ### end Alembic commands ###
